# Generated by Django 4.0.4 on 2022-05-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_rename_subscribers_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
    ]
