# Generated by Django 4.0.4 on 2022-05-19 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_customeraddress_order_totalamount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='totalAmount',
            new_name='totalPrice',
        ),
    ]
