# Generated by Django 4.0.4 on 2022-06-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_user_alter_order_customerphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
