# Generated by Django 4.0.4 on 2022-05-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='isMain',
            field=models.BooleanField(default=False),
        ),
    ]
